# Generated by Django 2.1.1 on 2018-09-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbols', models.CharField(default=0, max_length=4, unique=True, verbose_name='symbols')),
                ('status', models.SmallIntegerField(choices=[(0, 'new'), (1, 'given'), (2, 'used')], verbose_name='status')),
            ],
            options={
                'verbose_name': 'key',
                'verbose_name_plural': 'keys',
            },
        ),
    ]
